title: 90-day summer grind
email: your-email@example.com
description: >-
  A daily log of progress in trading and Chinese language learning.
baseurl: "" # the subpath of your site, e.g. /blog. If hosted at the root, leave empty.
url: "" # the base hostname & protocol for your site, e.g. http://example.com. If planning to use GitHub Pages, it will be like http://username.github.io

# Build settings
markdown: kramdown
theme: minima # You can change this or remove it if you're using custom layouts heavily
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/ 